;;;;

(defpackage :saexplorer.explorer
  (:nicknames :explorer)
  (:use :cl)
  (:import-from :cl-log
                #:log-message)
  (:import-from :saexplorer
                #:split-keywords)
  (:import-from :saexplorer.scopus
                #:proximity)
  (:export #:explore))


(in-package :saexplorer.explorer)

(defclass <search-results> ()
  ((matched-entries :initarg :entries :accessor entries
                    :documentation "A list of records returned by search engine.")
   (facets :initarg :facets :initform nil))
  (:documentation "Parsed results from bibliography system."))


(defun parse-result (content)
  "Parse document returned by Scopus and creates instance of `<search-results>' class."
  (let ((json (cl-json:decode-json-from-string content)))
    (make-instance '<search-results>
                   :matched-entries (scopus::get-json-item json '(:search-results :entry))
                   :facets (scopus::get-json-item json '(:search-results :facet)))))



(defun process-item (start content)
  (declare (ignore start))
  (let* ((json (cl-json:decode-json-from-string content))
         (entries (scopus::get-json-item json '(:search-results :entry))))
    (dolist (entry entries)
      (log-message :info "~A" (scopus::get-json-item entry '(:prism\:publication-name))))))


(defun scopus->entries (scopus-results)
  "Convert Scopus search result into list of parsed entries."
  (mapcan #'(lambda (chunk-content)
              (scopus::get-json-item (cl-json:decode-json-from-string chunk-content)
                                     '(:search-results :entry)))
          scopus-results))

(defun scopus->facets (scopus-results)
  (scopus::get-json-item
   (cl-json:decode-json-from-string (first scopus-results)) '(:search-results :facet)))


;;; Main function
(defun explore (keywords)
  t)


;;;


;; proceedings
#+(or)((:@--FA . "true")
 (:LINK ((:@--FA . "true") (:@REF . "self") (:@HREF . "http://api.elsevier.com/content/abstract/scopus_id/85032292725")) ((:@--FA . "true") (:@REF . "author-affiliation") (:@HREF . "http://api.elsevier.com/content/abstract/scopus_id/85032292725?field=author,affiliation")) ((:@--FA . "true") (:@REF . "scopus") (:@HREF . "https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85032292725&origin=inward")) ((:@--FA . "true") (:@REF . "scopus-citedby") (:@HREF . "https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85032292725&origin=inward")))
 (:PRISM\:URL . "http://api.elsevier.com/content/abstract/scopus_id/85032292725")
 (:DC\:IDENTIFIER . "SCOPUS_ID:85032292725")
 (:EID . "2-s2.0-85032292725")
 (:DC\:TITLE . "An overview of access control mechanisms for internet of things")
 (:DC\:CREATOR . "Alramadhan M.")
 (:PRISM\:PUBLICATION-NAME . "2017 26th International Conference on Computer Communications and Networks, ICCCN 2017")
 (:PRISM\:ISBN . "9781509029914")
 (:PRISM\:PAGE-RANGE)
 (:PRISM\:COVER-DATE . "2017-09-14")
 (:PRISM\:COVER-DISPLAY-DATE . "14 September 2017")
 (:PRISM\:DOI . "10.1109/ICCCN.2017.8038503")
 (:DC\:DESCRIPTION . "© 2017 IEEE. The integration of the physical world and the cyber system in IoT brings significant challenges to the design of security solutions. Access control is considered to be a critical system component for the protection of data, cyberinfrastructure, and even the physical systems in IoT; however, because of the new characteristics of IoT systems, such as the resource constraints, the large scale and the device heterogeneity, many traditional security solutions including existing access control mechanisms may not be directly applicable in IoT environment. This paper first presents an overview of the existing access control mechanisms and analyzes their applicability in IoT systems. Then, both the challenges in the IoT access control design and the goals for future IoT access control design are identified and discussed.")
 (:CITEDBY-COUNT . "0")
 (:AFFILIATION ((:@--FA . "true")
                (:AFFILIATION-URL . "http://api.elsevier.com/content/affiliation/affiliation_id/60019245")
                (:AFID . "60019245")
                (:AFFILNAME . "University of Houston-Clear Lake")
                (:AFFILIATION-CITY . "Houston")
                (:AFFILIATION-COUNTRY . "United States"))
               ((:@--FA . "true")
                (:AFFILIATION-URL . "http://api.elsevier.com/content/affiliation/affiliation_id/60019245")
                (:AFID . "60019245")
                (:AFFILNAME . "University of Houston-Clear Lake")
                (:AFFILIATION-CITY . "Houston") (:AFFILIATION-COUNTRY . "United States")))
 (:PRISM\:AGGREGATION-TYPE . "Conference Proceeding")
 (:SUBTYPE . "cp")
 (:SUBTYPE-DESCRIPTION . "Conference Paper")
 (:AUTHOR-COUNT (:@LIMIT . "100") (:$ . "3"))
 (:AUTHOR ((:@--FA . "true")
           (:@SEQ . "1")
           (:AUTHOR-URL . "http://api.elsevier.com/content/author/author_id/57196224141")
           (:AUTHID . "57196224141")
           (:AUTHNAME . "Alramadhan M.")
           (:SURNAME . "Alramadhan")
           (:GIVEN-NAME . "Mousa")
           (:INITIALS . "M.")
           (:AFID ((:@--FA . "true") (:$ . "60019245"))))
          ((:@--FA . "true") (:@SEQ . "2") (:AUTHOR-URL . "http://api.elsevier.com/content/author/author_id/9271953200") (:AUTHID . "9271953200") (:AUTHNAME . "Sha K.") (:SURNAME . "Sha") (:GIVEN-NAME . "Kewei") (:INITIALS . "K.") (:AFID ((:@--FA . "true") (:$ . "60019245")) ((:@--FA . "true") (:$ . "60019245"))))
          ((:@--FA . "true") (:@SEQ . "2") (:AUTHOR-URL . "http://api.elsevier.com/content/author/author_id/9271953200") (:AUTHID . "9271953200") (:AUTHNAME . "Sha K.") (:SURNAME . "Sha") (:GIVEN-NAME . "Kewei") (:INITIALS . "K.") (:AFID ((:@--FA . "true") (:$ . "60019245")) ((:@--FA . "true") (:$ . "60019245")))))
 (:AUTHKEYWORDS . "Access control | Attribute-based access control (ABAC) | Attribute-based access control (ABAC) | Capability-based access control (CapBAC) | Internet of things | IoT | Role-based access control (RBAC)")
 (:ARTICLE-NUMBER . "8038503")
 (:SOURCE-ID . "21100835670")
 (:FUND-ACR . "NSFC")
 (:FUND-NO . "61373006")
 (:FUND-SPONSOR . "National Natural Science Foundation of China"))

;; article
#+(or)((:@--FA . "true")
  (:LINK ((:@--FA . "true")
          (:@REF . "self")
          (:@HREF . "http://api.elsevier.com/content/abstract/scopus_id/85034429128"))
         ((:@--FA . "true") (:@REF . "author-affiliation") (:@HREF . "http://api.elsevier.com/content/abstract/scopus_id/85034429128?field=author,affiliation"))
         ((:@--FA . "true") (:@REF . "scopus") (:@HREF . "https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85034429128&origin=inward"))
         ((:@--FA . "true") (:@REF . "scopus-citedby") (:@HREF . "https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85034429128&origin=inward")))
  (:PRISM\:URL . "http://api.elsevier.com/content/abstract/scopus_id/85034429128")
  (:DC\:IDENTIFIER . "SCOPUS_ID:85034429128")
  (:EID . "2-s2.0-85034429128")
  (:DC\:TITLE . "Habitus, affordances, and family leisure: Cultural reproduction through children’s leisure activities")
  (:DC\:CREATOR . "Choi K.")
  (:PRISM\:PUBLICATION-NAME . "Ethnography")
  (:PRISM\:ISSN . "14661381")
  (:PRISM\:E-ISSN . "17412714")
  (:PRISM\:VOLUME . "18")
  (:PRISM\:ISSUE-IDENTIFIER . "4")
  (:PRISM\:PAGE-RANGE . "427-449")
  (:PRISM\:COVER-DATE . "2017-12-01")
  (:PRISM\:COVER-DISPLAY-DATE . "1 December 2017")
  (:PRISM\:DOI . "10.1177/1466138116674734")
  (:DC\:DESCRIPTION . "© 2016, © The British Association of Hand Therapists Ltd 2016. Informed by Gibson’s affordances and Bourdieu’s habitus, this visual ethnographic study explores parents’ ideas about learning and leisure and the actual domestic leisure children (between three to seven years old) consume in association with socioeconomic status. It is found that parent informants have similar reservations about local education regardless of socioeconomic status. Nevertheless, their different socioeconomic and cultural backgrounds contribute to their different involvement in children’s learning and leisure through their use of the domestic setup, television and computing devices, and toys. Through leisure, middle-class parent informants transmit certain emotions, values, skills, behavioral dispositions, and tastes to their children, which coincide with institutional approaches to learning. The study finds that children’s domestic leisure is largely patterned by materials (domestic setup and leisure-induced appliances), practices (TV and mobile computing usage and toy selection and play) and social structure, and thus links considerably to children’s disparity in academic achievements and attitudes towards learning.")
  (:CITEDBY-COUNT . "0")
  (:AFFILIATION ((:@--FA . "true")
                 (:AFFILIATION-URL . "http://api.elsevier.com/content/affiliation/affiliation_id/60013983")
                 (:AFID . "60013983")
                 (:AFFILNAME . "City University of Hong Kong")
                 (:AFFILIATION-CITY . "Hong Kong")
                 (:AFFILIATION-COUNTRY . "China")))
  (:PRISM\:AGGREGATION-TYPE . "Journal")
  (:SUBTYPE . "ar")
  (:SUBTYPE-DESCRIPTION . "Article")
  (:AUTHOR-COUNT (:@LIMIT . "100") (:$ . "1"))
  (:AUTHOR ((:@--FA . "true")
            (:@SEQ . "1")
            (:AUTHOR-URL . "http://api.elsevier.com/content/author/author_id/42461176600")
            (:AUTHID . "42461176600")
            (:AUTHNAME . "Choi K.")
            (:SURNAME . "Choi")
            (:GIVEN-NAME . "Kimburley W.Y.")
            (:INITIALS . "K.W.Y.")
            (:AFID ((:@--FA . "true") (:$ . "60013983")))))
  (:AUTHKEYWORDS . "affordances | class | habitus | Hong Kong | learning | leisure | parenting | reproduction")
  (:SOURCE-ID . "5600155023")
  (:FUND-ACR . "RGC, UGC")
  (:FUND-NO . "159613")
  (:FUND-SPONSOR . "Research Grants Council, University Grants Committee"))


#|
(((NAME . exactsrctitle)
  (ATTRIBUTE . exactsrctitle)
  (CATEGORY ((VALUE . Lecture Notes In Computer Science Including Subseries Lecture Notes In Artificial Intelligence And Lecture Notes In Bioinformatics)
             (NAME . Lecture Notes In Computer Science Including Subseries Lecture Notes In Artificial Intelligence And Lecture Notes In Bioinformatics)
             (HIT-COUNT . 58))
            ((VALUE . Alpine And Mediterranean Quaternary) (NAME . Alpine And Mediterranean Quaternary) (HIT-COUNT . 13))
            ((VALUE . International Journal Of Foundations Of Computer Science) (NAME . International Journal Of Foundations Of Computer Science) (HIT-COUNT . 12))
            ((VALUE . Theoretical Computer Science) (NAME . Theoretical Computer Science) (HIT-COUNT . 8))
            ((VALUE . Theory Of Computing Systems) (NAME . Theory Of Computing Systems) (HIT-COUNT . 7))
            ((VALUE . Bollettino Della Societa Geologica Italiana) (NAME . Bollettino Della Societa Geologica Italiana) (HIT-COUNT . 6))
            ((VALUE . Fundamenta Informaticae) (NAME . Fundamenta Informaticae) (HIT-COUNT . 6))
            ((VALUE . Leibniz International Proceedings In Informatics Lipics) (NAME . Leibniz International Proceedings In Informatics Lipics) (HIT-COUNT . 6))
            ((VALUE . Proceedings Of SPIE The International Society For Optical Engineering) (NAME . Proceedings Of SPIE The International Society For Optical Engineering) (HIT-COUNT . 6))
            ((VALUE . Acta Cybernetica) (NAME . Acta Cybernetica) (HIT-COUNT . 5))
            ((VALUE . Discrete Applied Mathematics) (NAME . Discrete Applied Mathematics) (HIT-COUNT . 4))
            ((VALUE . Information And Computation) (NAME . Information And Computation) (HIT-COUNT . 4))
            ((VALUE . Information Processing Letters) (NAME . Information Processing Letters) (HIT-COUNT . 4))
            ((VALUE . Lecture Notes In Computer Science) (NAME . Lecture Notes In Computer Science) (HIT-COUNT . 4))
            ((VALUE . Acta Informatica) (NAME . Acta Informatica) (HIT-COUNT . 3))
            ((VALUE . Economic And Political Weekly) (NAME . Economic And Political Weekly) (HIT-COUNT . 3))
            ((VALUE . Machine Translation) (NAME . Machine Translation) (HIT-COUNT . 3))
            ((VALUE . Rivista Italiana Di Paleontologia E Stratigrafia) (NAME . Rivista Italiana Di Paleontologia E Stratigrafia) (HIT-COUNT . 3))
            ((VALUE . Bollettino Della Societa Geologica Italiana Supplemento) (NAME . Bollettino Della Societa Geologica Italiana Supplemento) (HIT-COUNT . 2))
            ((VALUE . Canadian Geotechnical Journal) (NAME . Canadian Geotechnical Journal) (HIT-COUNT . 2))
            ((VALUE . Comptes Rendus De L Academie De Sciences Serie Iia Sciences De La Terre Et Des Planetes) (NAME . Comptes Rendus De L Academie De Sciences Serie Iia Sciences De La Terre Et Des Planetes) (HIT-COUNT . 2))
            ((VALUE . Electronic Proceedings In Theoretical Computer Science Eptcs) (NAME . Electronic Proceedings In Theoretical Computer Science Eptcs) (HIT-COUNT . 2))
            ((VALUE . Grammars) (NAME . Grammars) (HIT-COUNT . 2))
            ((VALUE . IEEE Transactions On Magnetics) (NAME . IEEE Transactions On Magnetics) (HIT-COUNT . 2))
            ((VALUE . Journal Of Computer And System Sciences) (NAME . Journal Of Computer And System Sciences) (HIT-COUNT . 2))
            ((VALUE . Journal Of Information Storage And Processing Systems) (NAME . Journal Of Information Storage And Processing Systems) (HIT-COUNT . 2))
            ((VALUE . Journal Of Magnetism And Magnetic Materials) (NAME . Journal Of Magnetism And Magnetic Materials) (HIT-COUNT . 2))
            ((VALUE . Periodico Di Mineralogia) (NAME . Periodico Di Mineralogia) (HIT-COUNT . 2))
            ((VALUE . Proceedings Of The Institution Of Mechanical Engineers Part J Journal Of Engineering Tribology) (NAME . Proceedings Of The Institution Of Mechanical Engineers Part J Journal Of Engineering Tribology) (HIT-COUNT . 2))
            ((VALUE . Proceedings Symposium On Logic In Computer Science) (NAME . Proceedings Symposium On Logic In Computer Science) (HIT-COUNT . 2))))
 ((NAME . au-id)
  (ATTRIBUTE . au-id)
  (CATEGORY ((VALUE . 7101633955) (NAME . 7101633955) (HIT-COUNT . 16)) ((VALUE . 8925402600) (NAME . 8925402600) (HIT-COUNT . 10)) ((VALUE . 14045708600) (NAME . 14045708600) (HIT-COUNT . 7)) ((VALUE . 7005428680) (NAME . 7005428680) (HIT-COUNT . 7)) ((VALUE . 8220258100) (NAME . 8220258100) (HIT-COUNT . 7)) ((VALUE . 55885981800) (NAME . 55885981800) (HIT-COUNT . 6)) ((VALUE . 6603386969) (NAME . 6603386969) (HIT-COUNT . 6)) ((VALUE . 6701782293) (NAME . 6701782293) (HIT-COUNT . 6)) ((VALUE . 35564010500) (NAME . 35564010500) (HIT-COUNT . 5)) ((VALUE . 56261383400) (NAME . 56261383400) (HIT-COUNT . 5)) ((VALUE . 7003846159) (NAME . 7003846159) (HIT-COUNT . 5)) ((VALUE . 7004633256) (NAME . 7004633256) (HIT-COUNT . 5)) ((VALUE . 36727738700) (NAME . 36727738700) (HIT-COUNT . 4)) ((VALUE . 55975496900) (NAME . 55975496900) (HIT-COUNT . 4)) ((VALUE . 7003349112) (NAME . 7003349112) (HIT-COUNT . 4)) ((VALUE . 7003536109) (NAME . 7003536109) (HIT-COUNT . 4)) ((VALUE . 7403366142) (NAME . 7403366142) (HIT-COUNT . 4)) ((VALUE . 8552126700) (NAME . 8552126700) (HIT-COUNT . 4)) ((VALUE . 8931578400) (NAME . 8931578400) (HIT-COUNT . 4)) ((VALUE . 14047062400) (NAME . 14047062400) (HIT-COUNT . 3)) ((VALUE . 16318853900) (NAME . 16318853900) (HIT-COUNT . 3)) ((VALUE . 35070526200) (NAME . 35070526200) (HIT-COUNT . 3)) ((VALUE . 35584084400) (NAME . 35584084400) (HIT-COUNT . 3)) ((VALUE . 36047486700) (NAME . 36047486700) (HIT-COUNT . 3)) ((VALUE . 36602797900) (NAME . 36602797900) (HIT-COUNT . 3)) ((VALUE . 55756757900) (NAME . 55756757900) (HIT-COUNT . 3)) ((VALUE . 56036884700) (NAME . 56036884700) (HIT-COUNT . 3)) ((VALUE . 6602417015) (NAME . 6602417015) (HIT-COUNT . 3)) ((VALUE . 6602588106) (NAME . 6602588106) (HIT-COUNT . 3)) ((VALUE . 7005043284) (NAME . 7005043284) (HIT-COUNT . 3))))
 ((NAME . authname)
  (ATTRIBUTE . scoprefnameauid)
  (CATEGORY ((VALUE . Otto, F.#7101633955) (NAME . Otto, F.#7101633955) (HIT-COUNT . 16))
            ((VALUE . Jurdziński, T.#8925402600) (NAME . Jurdziński, T.#8925402600) (HIT-COUNT . 10))
            ((VALUE . Maletti, A.#8220258100) (NAME . Maletti, A.#8220258100) (HIT-COUNT . 7))
            ((VALUE . Mráz, F.#14045708600) (NAME . Mráz, F.#14045708600) (HIT-COUNT . 7))
            ((VALUE . Vogler, H.#7005428680) (NAME . Vogler, H.#7005428680) (HIT-COUNT . 7))
            ((VALUE . Fülöp, Z.#55885981800) (NAME . Fülöp, Z.#55885981800) (HIT-COUNT . 6))
            ((VALUE . Kutrib, M.#6701782293) (NAME . Kutrib, M.#6701782293) (HIT-COUNT . 6))
            ((VALUE . Droste, M.#7003846159) (NAME . Droste, M.#7003846159) (HIT-COUNT . 5))
            ((VALUE . Fernau, H.#56261383400) (NAME . Fernau, H.#56261383400) (HIT-COUNT . 5))
            ((VALUE . Okhotin, A.#7004633256) (NAME . Okhotin, A.#7004633256) (HIT-COUNT . 5))
            ((VALUE . Plátek, M.#6603386969) (NAME . Plátek, M.#6603386969) (HIT-COUNT . 5))
            ((VALUE . Heinen, S.#7003536109) (NAME . Heinen, S.#7003536109) (HIT-COUNT . 4))
            ((VALUE . Jirásková, G.#8552126700) (NAME . Jirásková, G.#8552126700) (HIT-COUNT . 4))
            ((VALUE . Lohaus, L.#36727738700) (NAME . Lohaus, L.#36727738700) (HIT-COUNT . 4))
            ((VALUE . Rossius, A.#55975496900) (NAME . Rossius, A.#55975496900) (HIT-COUNT . 4))
            ((VALUE . Talke, F.E.#35564010500) (NAME . Talke, F.E.#35564010500) (HIT-COUNT . 4))
            ((VALUE . Tan, S.#7403366142) (NAME . Tan, S.#7403366142) (HIT-COUNT . 4))
            ((VALUE . Wunderlich, R.#8931578400) (NAME . Wunderlich, R.#8931578400) (HIT-COUNT . 4))
            ((VALUE . Anselmo, M.#8513219100) (NAME . Anselmo, M.#8513219100) (HIT-COUNT . 3))
            ((VALUE . Bhushan, B.#36047486700) (NAME . Bhushan, B.#36047486700) (HIT-COUNT . 3))
            ((VALUE . Blankson, I.M.#6602417015) (NAME . Blankson, I.M.#6602417015) (HIT-COUNT . 3))
            ((VALUE . Dassow, J.#55756757900) (NAME . Dassow, J.#55756757900) (HIT-COUNT . 3))
            ((VALUE . Dhanasar, M.#16318853900) (NAME . Dhanasar, M.#16318853900) (HIT-COUNT . 3))
            ((VALUE . Domaratzki, M.#6602588106) (NAME . Domaratzki, M.#6602588106) (HIT-COUNT . 3))
            ((VALUE . Ferguson, F.#7005043284) (NAME . Ferguson, F.#7005043284) (HIT-COUNT . 3))
            ((VALUE . Holzer, M.#7006648424) (NAME . Holzer, M.#7006648424) (HIT-COUNT . 3))
            ((VALUE . Kufleitner, M.#14047062400) (NAME . Kufleitner, M.#14047062400) (HIT-COUNT . 3))
            ((VALUE . Lauser, A.#36602797900) (NAME . Lauser, A.#36602797900) (HIT-COUNT . 3))
            ((VALUE . Madonia, M.#8513219000) (NAME . Madonia, M.#8513219000) (HIT-COUNT . 3))
            ((VALUE . Othman, M.#56036884700) (NAME . Othman, M.#56036884700) (HIT-COUNT . 3))))
 ((NAME . pubyear) (ATTRIBUTE . pubyear) (CATEGORY ((VALUE . 2017) (NAME . 2017) (HIT-COUNT . 18)) ((VALUE . 2016) (NAME . 2016) (HIT-COUNT . 18)) ((VALUE . 2015) (NAME . 2015) (HIT-COUNT . 28)) ((VALUE . 2014) (NAME . 2014) (HIT-COUNT . 20)) ((VALUE . 2013) (NAME . 2013) (HIT-COUNT . 16)) ((VALUE . 2012) (NAME . 2012) (HIT-COUNT . 25)) ((VALUE . 2011) (NAME . 2011) (HIT-COUNT . 24)) ((VALUE . 2010) (NAME . 2010) (HIT-COUNT . 23)) ((VALUE . 2009) (NAME . 2009) (HIT-COUNT . 25)) ((VALUE . 2008) (NAME . 2008) (HIT-COUNT . 12)) ((VALUE . 2007) (NAME . 2007) (HIT-COUNT . 9)) ((VALUE . 2006) (NAME . 2006) (HIT-COUNT . 16)) ((VALUE . 2005) (NAME . 2005) (HIT-COUNT . 19)) ((VALUE . 2004) (NAME . 2004) (HIT-COUNT . 17)) ((VALUE . 2003) (NAME . 2003) (HIT-COUNT . 12)) ((VALUE . 2002) (NAME . 2002) (HIT-COUNT . 12)) ((VALUE . 2001) (NAME . 2001) (HIT-COUNT . 10)) ((VALUE . 2000) (NAME . 2000) (HIT-COUNT . 7)) ((VALUE . 1999) (NAME . 1999) (HIT-COUNT . 8)) ((VALUE . 1998) (NAME . 1998) (HIT-COUNT . 8)) ((VALUE . 1997) (NAME . 1997) (HIT-COUNT . 10)) ((VALUE . 1996) (NAME . 1996) (HIT-COUNT . 4)) ((VALUE . 1995) (NAME . 1995) (HIT-COUNT . 5)) ((VALUE . 1994) (NAME . 1994) (HIT-COUNT . 2)) ((VALUE . 1992) (NAME . 1992) (HIT-COUNT . 1)) ((VALUE . 1991) (NAME . 1991) (HIT-COUNT . 1)) ((VALUE . 1989) (NAME . 1989) (HIT-COUNT . 1)) ((VALUE . 1988) (NAME . 1988) (HIT-COUNT . 1)) ((VALUE . 1986) (NAME . 1986) (HIT-COUNT . 2)) ((VALUE . 1982) (NAME . 1982) (HIT-COUNT . 1))))
 ((NAME . subjarea) (ATTRIBUTE . subjarea) (CATEGORY ((LABEL . Computer Science (all)) (ID . 1700) (VALUE . COMP) (NAME . COMP) (HIT-COUNT . 195)) ((LABEL . Mathematics (all)) (ID . 2600) (VALUE . MATH) (NAME . MATH) (HIT-COUNT . 133)) ((LABEL . Engineering (all)) (ID . 2200) (VALUE . ENGI) (NAME . ENGI) (HIT-COUNT . 67)) ((LABEL . Earth and Planetary Sciences (all)) (ID . 1900) (VALUE . EART) (NAME . EART) (HIT-COUNT . 59)) ((LABEL . Arts and Humanities (all)) (ID . 1200) (VALUE . ARTS) (NAME . ARTS) (HIT-COUNT . 35)) ((LABEL . Social Sciences (all)) (ID . 3300) (VALUE . SOCI) (NAME . SOCI) (HIT-COUNT . 28)) ((LABEL . Physics and Astronomy (all)) (ID . 3100) (VALUE . PHYS) (NAME . PHYS) (HIT-COUNT . 19)) ((LABEL . Materials Science (all)) (ID . 2500) (VALUE . MATE) (NAME . MATE) (HIT-COUNT . 18)) ((LABEL . Medicine (all)) (ID . 2700) (VALUE . MEDI) (NAME . MEDI) (HIT-COUNT . 18)) ((LABEL . Agricultural and Biological Sciences (all)) (ID . 1100) (VALUE . AGRI) (NAME . AGRI) (HIT-COUNT . 10)) ((LABEL . Energy (all)) (ID . 2100) (VALUE . ENER) (NAME . ENER) (HIT-COUNT . 9)) ((LABEL . Environmental Science (all)) (ID . 2300) (VALUE . ENVI) (NAME . ENVI) (HIT-COUNT . 7)) ((LABEL . Biochemistry, Genetics and Molecular Biology (all)) (ID . 1300) (VALUE . BIOC) (NAME . BIOC) (HIT-COUNT . 6)) ((LABEL . Business, Management and Accounting (all)) (ID . 1400) (VALUE . BUSI) (NAME . BUSI) (HIT-COUNT . 6)) ((LABEL . Health Professions  (all)) (ID . 3600) (VALUE . HEAL) (NAME . HEAL) (HIT-COUNT . 5)) ((LABEL . Psychology (all)) (ID . 3200) (VALUE . PSYC) (NAME . PSYC) (HIT-COUNT . 4)) ((LABEL . Decision Sciences (all)) (ID . 1800) (VALUE . DECI) (NAME . DECI) (HIT-COUNT . 3)) ((LABEL . Economics, Econometrics and Finance (all)) (ID . 2000) (VALUE . ECON) (NAME . ECON) (HIT-COUNT . 3)) ((LABEL . Chemical Engineering (all)) (ID . 1500) (VALUE . CENG) (NAME . CENG) (HIT-COUNT . 1)) ((LABEL . Chemistry (all)) (ID . 1600) (VALUE . CHEM) (NAME . CHEM) (HIT-COUNT . 1)) ((LABEL . Immunology and Microbiology (all)) (ID . 2400) (VALUE . IMMU) (NAME . IMMU) (HIT-COUNT . 1)) ((LABEL . Multidisciplinary) (ID . 1000) (VALUE . MULT) (NAME . MULT) (HIT-COUNT . 1)) ((LABEL . Neuroscience (all)) (ID . 2800) (VALUE . NEUR) (NAME . NEUR) (HIT-COUNT . 1)) ((LABEL . Nursing (all)) (ID . 2900) (VALUE . NURS) (NAME . NURS) (HIT-COUNT . 1)) ((LABEL . Pharmacology, Toxicology and Pharmaceutics (all)) (ID . 3000) (VALUE . PHAR) (NAME . PHAR) (HIT-COUNT . 1))))
 ((NAME . language)
  (ATTRIBUTE . language)
  (CATEGORY ((VALUE . English) (NAME . English) (HIT-COUNT . 341))
            ((VALUE . Italian) (NAME . Italian) (HIT-COUNT . 14))
            ((VALUE . French) (NAME . French) (HIT-COUNT . 3))
            ((VALUE . Portuguese) (NAME . Portuguese) (HIT-COUNT . 2))
            ((VALUE . Chinese) (NAME . Chinese) (HIT-COUNT . 1))
            ((VALUE . German) (NAME . German) (HIT-COUNT . 1))
            ((VALUE . Lithuanian) (NAME . Lithuanian) (HIT-COUNT . 1))
            ((VALUE . Russian) (NAME . Russian) (HIT-COUNT . 1))))
 ((NAME . af-id) (ATTRIBUTE . af-id) (CATEGORY ((LABEL) (ID . affiliation_id:60018123) (VALUE . 60018123) (NAME . Universitat Kassel) (HIT-COUNT . 16)) ((LABEL) (ID . affiliation_id:60016147) (VALUE . 60016147) (NAME . University of Wroclaw) (HIT-COUNT . 11)) ((LABEL) (ID . affiliation_id:60008042) (VALUE . 60008042) (NAME . Universitat Leipzig) (HIT-COUNT . 9)) ((LABEL) (ID . affiliation_id:60015815) (VALUE . 60015815) (NAME . Universitat Stuttgart) (HIT-COUNT . 9)) ((LABEL) (ID . affiliation_id:60016605) (VALUE . 60016605) (NAME . Charles University) (HIT-COUNT . 9)) ((LABEL) (ID . affiliation_id:60018353) (VALUE . 60018353) (NAME . Technische Universitat Dresden) (HIT-COUNT . 9)) ((LABEL) (ID . affiliation_id:60032350) (VALUE . 60032350) (NAME . Universita degli Studi di Roma La Sapienza) (HIT-COUNT . 9)) ((LABEL) (ID . affiliation_id:60016005) (VALUE . 60016005) (NAME . Queen's University, Kingston) (HIT-COUNT . 8)) ((LABEL) (ID . affiliation_id:60017134) (VALUE . 60017134) (NAME . Justus Liebig University Giessen) (HIT-COUNT . 7)) ((LABEL) (ID . affiliation_id:60006876) (VALUE . 60006876) (NAME . Turun yliopisto) (HIT-COUNT . 6)) ((LABEL) (ID . affiliation_id:60008134) (VALUE . 60008134) (NAME . CNRS Centre National de la Recherche Scientifique) (HIT-COUNT . 6)) ((LABEL) (ID . affiliation_id:60027332) (VALUE . 60027332) (NAME . Szegedi Tudomanyegyetem (SZTE)) (HIT-COUNT . 6)) ((LABEL) (ID . affiliation_id:60000243) (VALUE . 60000243) (NAME . Istituto Nazionale Di Geofisica E Vulcanologia, Rome) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60004981) (VALUE . 60004981) (NAME . Ecole Normale Superieure de Cachan) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60010146) (VALUE . 60010146) (NAME . Universita degli Studi di Catania) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60016653) (VALUE . 60016653) (NAME . Rheinisch-Westfalische Technische Hochschule Aachen) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60017293) (VALUE . 60017293) (NAME . Universita degli Studi di Napoli Federico II) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60021199) (VALUE . 60021199) (NAME . Consiglio Nazionale delle Ricerche) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60021859) (VALUE . 60021859) (NAME . Universita degli Studi di Firenze) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60030612) (VALUE . 60030612) (NAME . University of California, San Diego) (HIT-COUNT . 5)) ((LABEL) (ID . affiliation_id:60001675) (VALUE . 60001675) (NAME . Turku Centre for Computer Science) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60005711) (VALUE . 60005711) (NAME . Universite Paris 7- Denis Diderot) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60007061) (VALUE . 60007061) (NAME . Universita di Salerno) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60010330) (VALUE . 60010330) (NAME . Slovak Academy of Sciences) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60010884) (VALUE . 60010884) (NAME . Western University) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60011891) (VALUE . 60011891) (NAME . Universitat Trier) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60018362) (VALUE . 60018362) (NAME . Otto von Guericke University of Magdeburg) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60026717) (VALUE . 60026717) (NAME . NASA Glenn Research Center) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60030318) (VALUE . 60030318) (NAME . Universita degli Studi di Milano) (HIT-COUNT . 4)) ((LABEL) (ID . affiliation_id:60031135) (VALUE . 60031135) (NAME . Academy of Sciences of the Czech Republic) (HIT-COUNT . 4))))
 ((NAME . exactkeyword)
  (ATTRIBUTE . exactkeyword)
  (CATEGORY ((VALUE . Automata Theory) (NAME . Automata Theory) (HIT-COUNT . 47))
            ((VALUE . Formal Languages) (NAME . Formal Languages) (HIT-COUNT . 25))
            ((VALUE . Algorithms) (NAME . Algorithms) (HIT-COUNT . 21))
            ((VALUE . Computer Science) (NAME . Computer Science) (HIT-COUNT . 21))
            ((VALUE . Computational Complexity) (NAME . Computational Complexity) (HIT-COUNT . 16))
            ((VALUE . Linguistics) (NAME . Linguistics) (HIT-COUNT . 16))
            ((VALUE . Context Free Languages) (NAME . Context Free Languages) (HIT-COUNT . 14))
            ((VALUE . Mathematical Models) (NAME . Mathematical Models) (HIT-COUNT . 14))
            ((VALUE . Photogrammetry) (NAME . Photogrammetry) (HIT-COUNT . 14))
            ((VALUE . Calibration) (NAME . Calibration) (HIT-COUNT . 13))
            ((VALUE . Forestry) (NAME . Forestry) (HIT-COUNT . 13))
            ((VALUE . Human) (NAME . Human) (HIT-COUNT . 13))
            ((VALUE . Italy) (NAME . Italy) (HIT-COUNT . 13))
            ((VALUE . Problem Solving) (NAME . Problem Solving) (HIT-COUNT . 13))
            ((VALUE . Article) (NAME . Article) (HIT-COUNT . 12))
            ((VALUE . Computational Linguistics) (NAME . Computational Linguistics) (HIT-COUNT . 12))
            ((VALUE . Finite Automata) (NAME . Finite Automata) (HIT-COUNT . 12))
            ((VALUE . Restarting Automata) (NAME . Restarting Automata) (HIT-COUNT . 12))
            ((VALUE . Cameras) (NAME . Cameras) (HIT-COUNT . 11))
            ((VALUE . Theorem Proving) (NAME . Theorem Proving) (HIT-COUNT . 11))
            ((VALUE . Weighted Tree) (NAME . Weighted Tree) (HIT-COUNT . 11))
            ((VALUE . Query Languages) (NAME . Query Languages) (HIT-COUNT . 10))
            ((VALUE . Translation (languages)) (NAME . Translation (languages)) (HIT-COUNT . 10))
            ((VALUE . Algebra) (NAME . Algebra) (HIT-COUNT . 9))
            ((VALUE . Artificial Intelligence) (NAME . Artificial Intelligence) (HIT-COUNT . 9))
            ((VALUE . Descriptional Complexity) (NAME . Descriptional Complexity) (HIT-COUNT . 9))
            ((VALUE . Expressive Power) (NAME . Expressive Power) (HIT-COUNT . 9))
            ((VALUE . Magnetic Tape) (NAME . Magnetic Tape) (HIT-COUNT . 9))
            ((VALUE . Pattern Matching) (NAME . Pattern Matching) (HIT-COUNT . 9))
            ((VALUE . Biomechanics) (NAME . Biomechanics) (HIT-COUNT . 8))))
 ((NAME . srctype) (ATTRIBUTE . srctype) (CATEGORY ((LABEL . Journal) (VALUE . j) (NAME . j) (HIT-COUNT . 214)) ((LABEL . Conference Proceeding) (VALUE . p) (NAME . p) (HIT-COUNT . 68)) ((LABEL . Book Series) (VALUE . k) (NAME . k) (HIT-COUNT . 65)) ((LABEL . Book) (VALUE . b) (NAME . b) (HIT-COUNT . 12))))
 ((NAME . country) (ATTRIBUTE . scoaffilctry)
  (CATEGORY ((VALUE . Germany) (NAME . Germany) (HIT-COUNT . 74))
            ((VALUE . Italy) (NAME . Italy) (HIT-COUNT . 56))
            ((VALUE . United States) (NAME . United States) (HIT-COUNT . 46))
            ((VALUE . United Kingdom) (NAME . United Kingdom) (HIT-COUNT . 27))
            ((VALUE . France) (NAME . France) (HIT-COUNT . 26))
            ((VALUE . China) (NAME . China) (HIT-COUNT . 24))
            ((VALUE . Poland) (NAME . Poland) (HIT-COUNT . 18))
            ((VALUE . Czech Republic) (NAME . Czech Republic) (HIT-COUNT . 17))
            ((VALUE . Canada) (NAME . Canada) (HIT-COUNT . 16))
            ((VALUE . Hungary) (NAME . Hungary) (HIT-COUNT . 11))
            ((VALUE . India) (NAME . India) (HIT-COUNT . 11))
            ((VALUE . Japan) (NAME . Japan) (HIT-COUNT . 11))
            ((VALUE . Netherlands) (NAME . Netherlands) (HIT-COUNT . 11))
            ((VALUE . Spain) (NAME . Spain) (HIT-COUNT . 11))
            ((VALUE . Finland) (NAME . Finland) (HIT-COUNT . 10))
            ((VALUE . Australia) (NAME . Australia) (HIT-COUNT . 7))
            ((VALUE . Slovakia) (NAME . Slovakia) (HIT-COUNT . 7))
            ((VALUE . Austria) (NAME . Austria) (HIT-COUNT . 5))
            ((VALUE . Portugal) (NAME . Portugal) (HIT-COUNT . 5))
            ((VALUE . Russian Federation) (NAME . Russian Federation) (HIT-COUNT . 5))
            ((VALUE . Greece) (NAME . Greece) (HIT-COUNT . 4))
            ((VALUE . Hong Kong) (NAME . Hong Kong) (HIT-COUNT . 4))
            ((VALUE . Malaysia) (NAME . Malaysia) (HIT-COUNT . 4))
            ((VALUE . South Africa) (NAME . South Africa) (HIT-COUNT . 4))
            ((VALUE . Thailand) (NAME . Thailand) (HIT-COUNT . 4))
            ((VALUE . Algeria) (NAME . Algeria) (HIT-COUNT . 3))
            ((VALUE . Brazil) (NAME . Brazil) (HIT-COUNT . 3))
            ((VALUE . Indonesia) (NAME . Indonesia) (HIT-COUNT . 3))
            ((VALUE . Sweden) (NAME . Sweden) (HIT-COUNT . 3))
            ((VALUE . Undefined) (NAME . Undefined) (HIT-COUNT . 7))))
 ((NAME . aucite)
  (ATTRIBUTE . aucite)
  (CATEGORY ((VALUE . Otto, F.) (NAME . Otto, F.) (HIT-COUNT . 16))
            ((VALUE . Jurdziński, T.) (NAME . Jurdziński, T.) (HIT-COUNT . 10))
            ((VALUE . Maletti, A.) (NAME . Maletti, A.) (HIT-COUNT . 7))
            ((VALUE . Mráz, F.) (NAME . Mráz, F.) (HIT-COUNT . 7))
            ((VALUE . Vogler, H.) (NAME . Vogler, H.) (HIT-COUNT . 7))
            ((VALUE . Fülöp, Z.) (NAME . Fülöp, Z.) (HIT-COUNT . 6))
            ((VALUE . Kutrib, M.) (NAME . Kutrib, M.) (HIT-COUNT . 6))
            ((VALUE . Droste, M.) (NAME . Droste, M.) (HIT-COUNT . 5))
            ((VALUE . Fernau, H.) (NAME . Fernau, H.) (HIT-COUNT . 5))
            ((VALUE . Okhotin, A.) (NAME . Okhotin, A.) (HIT-COUNT . 5))
            ((VALUE . Plátek, M.) (NAME . Plátek, M.) (HIT-COUNT . 5))
            ((VALUE . Heinen, S.) (NAME . Heinen, S.) (HIT-COUNT . 4))
            ((VALUE . Jirásková, G.) (NAME . Jirásková, G.) (HIT-COUNT . 4))
            ((VALUE . Lohaus, L.) (NAME . Lohaus, L.) (HIT-COUNT . 4))
            ((VALUE . Rossius, A.) (NAME . Rossius, A.) (HIT-COUNT . 4))
            ((VALUE . Talke, F.E.) (NAME . Talke, F.E.) (HIT-COUNT . 4))
            ((VALUE . Tan, S.) (NAME . Tan, S.) (HIT-COUNT . 4))
            ((VALUE . Wunderlich, R.) (NAME . Wunderlich, R.) (HIT-COUNT . 4))
            ((VALUE . Anselmo, M.) (NAME . Anselmo, M.) (HIT-COUNT . 3))
            ((VALUE . Araújo, D.) (NAME . Araújo, D.) (HIT-COUNT . 3))
            ((VALUE . Bhushan, B.) (NAME . Bhushan, B.) (HIT-COUNT . 3))
            ((VALUE . Blankson, I.M.) (NAME . Blankson, I.M.) (HIT-COUNT . 3))
            ((VALUE . Dassow, J.) (NAME . Dassow, J.) (HIT-COUNT . 3))
            ((VALUE . Dhanasar, M.) (NAME . Dhanasar, M.) (HIT-COUNT . 3))
            ((VALUE . Domaratzki, M.) (NAME . Domaratzki, M.) (HIT-COUNT . 3))
            ((VALUE . Ferguson, F.) (NAME . Ferguson, F.) (HIT-COUNT . 3))
            ((VALUE . Holzer, M.) (NAME . Holzer, M.) (HIT-COUNT . 3))
            ((VALUE . Kufleitner, M.) (NAME . Kufleitner, M.) (HIT-COUNT . 3))
            ((VALUE . Lauser, A.) (NAME . Lauser, A.) (HIT-COUNT . 3))
            ((VALUE . Madonia, M.) (NAME . Madonia, M.) (HIT-COUNT . 3)))))

|#
